version: '3.8'

services:
# d√πng chung
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db_main
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

# user service

  user_service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    container_name: ecommerce_user
    restart: always
    environment:
      PORT: 3004
      DB_HOST: postgres_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: 123456
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3004:3004"
    depends_on:
      postgres_db:
        condition: service_healthy

  catalogue_service:
    build:
      context: ./services/catalogue
      dockerfile: Dockerfile
    container_name: ecommerce_catalogue
    restart: always
    environment:
      PORT: 3002
      DB_HOST: postgres_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: 123456
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3002:3002"
    depends_on:
      postgres_db:
        condition: service_healthy

  order_service:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    container_name: ecommerce_order
    restart: always
    environment:
      PORT: 3003
      DB_HOST: postgres_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: 123456
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      PAYMENT_URL: http://payment_service:3005/api
    ports:
      - "3003:3003"
    depends_on:
      postgres_db:
        condition: service_healthy

  payment_service:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    container_name: ecommerce_payment
    restart: always
    environment:
      PORT: 3005
      DB_HOST: postgres_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: 123456
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      ORDER_URL: http://order_service:3003
    ports:
      - "3005:3005"

  cart_service:
    build:
      context: ./services/cart
      dockerfile: Dockerfile
    container_name: ecommerce_cart
    restart: always
    environment:
      PORT: 3006
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3006:3006"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: ./fontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - user_service
      - catalogue_service

volumes:
  postgres_data:
  redis_data:

