apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  
  DB_PASSWORD: SGFpTWV0Um9pMTIz  
  DB_DATABASE: ZWNvbW1lcmNlX2Ri   
  JWT_SECRET: Q2hhbmdlTWVUb0xvbmdSYW5kb21TdHJpbmdNaW5pbXVtMzJDaGFyYWN0ZXJzSGVyZTEyMzQ1Njc4OQ== 
  RABBITMQ_URL: YW1xcDovL2FkbWluOjEyMzQ1NkByYWJiaXRtcTo1NjcyLw==
  PAYMENT_URL: aHR0cDovL3BheW1lbnQtc2VydmljZTozMDA1L2FwaQ==  
  RABBITMQ_USER: YWRtaW4=
  RABBITMQ_PASS: MTIzNDU2
