apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "123456"
  DB_DATABASE: "ecommerce_db"
  JWT_SECRET: "change_me"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  PAYMENT_URL: "http://payment-service:3005/api"
